twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/form_div_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
when@test:
    twig:
        strict_variables: true
